# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/config.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.resize(400, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ConfigDialog.sizePolicy().hasHeightForWidth())
        ConfigDialog.setSizePolicy(sizePolicy)
        ConfigDialog.setMaximumSize(QtCore.QSize(16777215, 350))
        ConfigDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(ConfigDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.generalFormLayout = QtWidgets.QFormLayout(self.generalTab)
        self.generalFormLayout.setObjectName("generalFormLayout")
        self.configLabel = QtWidgets.QLabel(self.generalTab)
        self.configLabel.setObjectName("configLabel")
        self.generalFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.configLabel)
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setSpacing(6)
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        self.configComboBox = QtWidgets.QComboBox(self.generalTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configComboBox.sizePolicy().hasHeightForWidth())
        self.configComboBox.setSizePolicy(sizePolicy)
        self.configComboBox.setObjectName("configComboBox")
        self.buttonsHorizontalLayout.addWidget(self.configComboBox)
        self.editPushButton = QtWidgets.QPushButton(self.generalTab)
        self.editPushButton.setEnabled(False)
        self.editPushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.editPushButton.setObjectName("editPushButton")
        self.buttonsHorizontalLayout.addWidget(self.editPushButton)
        self.addToolButton = QtWidgets.QToolButton(self.generalTab)
        self.addToolButton.setObjectName("addToolButton")
        self.buttonsHorizontalLayout.addWidget(self.addToolButton)
        self.generalFormLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.buttonsHorizontalLayout)
        self.focusLabel = QtWidgets.QLabel(self.generalTab)
        self.focusLabel.setObjectName("focusLabel")
        self.generalFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.focusLabel)
        self.focusCheckBox = QtWidgets.QCheckBox(self.generalTab)
        self.focusCheckBox.setObjectName("focusCheckBox")
        self.generalFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.focusCheckBox)
        self.exitLabel = QtWidgets.QLabel(self.generalTab)
        self.exitLabel.setObjectName("exitLabel")
        self.generalFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.exitLabel)
        self.exitCheckBox = QtWidgets.QCheckBox(self.generalTab)
        self.exitCheckBox.setObjectName("exitCheckBox")
        self.generalFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.exitCheckBox)
        self.prettyLabel = QtWidgets.QLabel(self.generalTab)
        self.prettyLabel.setObjectName("prettyLabel")
        self.generalFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.prettyLabel)
        self.prettyCheckBox = QtWidgets.QCheckBox(self.generalTab)
        self.prettyCheckBox.setObjectName("prettyCheckBox")
        self.generalFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.prettyCheckBox)
        self.emptyDataLabel = QtWidgets.QLabel(self.generalTab)
        self.emptyDataLabel.setObjectName("emptyDataLabel")
        self.generalFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.emptyDataLabel)
        self.emptyDataCheckBox = QtWidgets.QCheckBox(self.generalTab)
        self.emptyDataCheckBox.setObjectName("emptyDataCheckBox")
        self.generalFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.emptyDataCheckBox)
        self.tabWidget.addTab(self.generalTab, "")
        self.compatibilityTab = QtWidgets.QWidget()
        self.compatibilityTab.setObjectName("compatibilityTab")
        self.compatibilityFormLayout = QtWidgets.QFormLayout(self.compatibilityTab)
        self.compatibilityFormLayout.setObjectName("compatibilityFormLayout")
        self.moveLabel = QtWidgets.QLabel(self.compatibilityTab)
        self.moveLabel.setObjectName("moveLabel")
        self.compatibilityFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.moveLabel)
        self.moveCheckBox = QtWidgets.QCheckBox(self.compatibilityTab)
        self.moveCheckBox.setText("")
        self.moveCheckBox.setObjectName("moveCheckBox")
        self.compatibilityFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.moveCheckBox)
        self.tabWidget.addTab(self.compatibilityTab, "")
        self.updatesTab = QtWidgets.QWidget()
        self.updatesTab.setObjectName("updatesTab")
        self.updatesFormLayout = QtWidgets.QFormLayout(self.updatesTab)
        self.updatesFormLayout.setObjectName("updatesFormLayout")
        self.apiLineEdit = QtWidgets.QLineEdit(self.updatesTab)
        self.apiLineEdit.setObjectName("apiLineEdit")
        self.updatesFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.apiLineEdit)
        self.apiLabel = QtWidgets.QLabel(self.updatesTab)
        self.apiLabel.setObjectName("apiLabel")
        self.updatesFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.apiLabel)
        self.tabWidget.addTab(self.updatesTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigDialog)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.configLabel.setBuddy(self.configComboBox)
        self.focusLabel.setBuddy(self.focusCheckBox)
        self.exitLabel.setBuddy(self.exitCheckBox)
        self.prettyLabel.setBuddy(self.prettyCheckBox)
        self.emptyDataLabel.setBuddy(self.emptyDataCheckBox)
        self.apiLabel.setBuddy(self.apiLineEdit)

        self.retranslateUi(ConfigDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(ConfigDialog.accept)
        self.buttonBox.rejected.connect(ConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Options - Mod Placer"))
        self.configLabel.setText(_translate("ConfigDialog", "Config"))
        self.editPushButton.setText(_translate("ConfigDialog", "Edit"))
        self.addToolButton.setText(_translate("ConfigDialog", "+"))
        self.focusLabel.setText(_translate("ConfigDialog", "Refresh on focus"))
        self.focusCheckBox.setToolTip(_translate("ConfigDialog", "Refresh mod and load order when application regains focus."))
        self.exitLabel.setText(_translate("ConfigDialog", "Save on exit"))
        self.exitCheckBox.setToolTip(_translate("ConfigDialog", "Save mod and load order when exiting program."))
        self.prettyLabel.setText(_translate("ConfigDialog", "Pretty print config"))
        self.prettyCheckBox.setToolTip(_translate("ConfigDialog", "Make JSON config files readable."))
        self.emptyDataLabel.setText(_translate("ConfigDialog", "Empty data folder"))
        self.emptyDataCheckBox.setToolTip(_translate("ConfigDialog", "Move all files to \"mods/Data Backup\" folder before linking new files."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("ConfigDialog", "General"))
        self.moveLabel.setText(_translate("ConfigDialog", "High level move"))
        self.moveCheckBox.setToolTip(_translate("ConfigDialog", "Use higher level move utility. More compatibility but slower.\n"
"Needed if data and mods folders are on different drives."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.compatibilityTab), _translate("ConfigDialog", "Compatibility"))
        self.apiLineEdit.setToolTip(_translate("ConfigDialog", "Needed for updates. Get one from Nexus > My Settings > API"))
        self.apiLabel.setText(_translate("ConfigDialog", "Nexus Api Key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updatesTab), _translate("ConfigDialog", "Updates"))
