# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/editconfig.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigEditDialog(object):
    def setupUi(self, ConfigEditDialog):
        ConfigEditDialog.setObjectName("ConfigEditDialog")
        ConfigEditDialog.resize(400, 300)
        ConfigEditDialog.setMaximumSize(QtCore.QSize(16777215, 300))
        ConfigEditDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigEditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(ConfigEditDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(ConfigEditDialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.gameLabel = QtWidgets.QLabel(ConfigEditDialog)
        self.gameLabel.setObjectName("gameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gameLabel)
        self.gameLineEdit = QtWidgets.QLineEdit(ConfigEditDialog)
        self.gameLineEdit.setObjectName("gameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gameLineEdit)
        self.dataLabel = QtWidgets.QLabel(ConfigEditDialog)
        self.dataLabel.setObjectName("dataLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dataLabel)
        self.dataHorizontalLayout = QtWidgets.QHBoxLayout()
        self.dataHorizontalLayout.setObjectName("dataHorizontalLayout")
        self.dataLineEdit = QtWidgets.QLineEdit(ConfigEditDialog)
        self.dataLineEdit.setObjectName("dataLineEdit")
        self.dataHorizontalLayout.addWidget(self.dataLineEdit)
        self.dataToolButton = QtWidgets.QToolButton(ConfigEditDialog)
        self.dataToolButton.setObjectName("dataToolButton")
        self.dataHorizontalLayout.addWidget(self.dataToolButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.dataHorizontalLayout)
        self.modsLabel = QtWidgets.QLabel(ConfigEditDialog)
        self.modsLabel.setObjectName("modsLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.modsLabel)
        self.modsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.modsHorizontalLayout.setObjectName("modsHorizontalLayout")
        self.modsLineEdit = QtWidgets.QLineEdit(ConfigEditDialog)
        self.modsLineEdit.setObjectName("modsLineEdit")
        self.modsHorizontalLayout.addWidget(self.modsLineEdit)
        self.modsToolButton = QtWidgets.QToolButton(ConfigEditDialog)
        self.modsToolButton.setObjectName("modsToolButton")
        self.modsHorizontalLayout.addWidget(self.modsToolButton)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.modsHorizontalLayout)
        self.pluginsLabel = QtWidgets.QLabel(ConfigEditDialog)
        self.pluginsLabel.setObjectName("pluginsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pluginsLabel)
        self.pluginsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.pluginsHorizontalLayout.setObjectName("pluginsHorizontalLayout")
        self.pluginsLineEdit = QtWidgets.QLineEdit(ConfigEditDialog)
        self.pluginsLineEdit.setObjectName("pluginsLineEdit")
        self.pluginsHorizontalLayout.addWidget(self.pluginsLineEdit)
        self.pluginsToolButton = QtWidgets.QToolButton(ConfigEditDialog)
        self.pluginsToolButton.setObjectName("pluginsToolButton")
        self.pluginsHorizontalLayout.addWidget(self.pluginsToolButton)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.pluginsHorizontalLayout)
        self.prefixLabel = QtWidgets.QLabel(ConfigEditDialog)
        self.prefixLabel.setObjectName("prefixLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.prefixLabel)
        self.prefixLineEdit = QtWidgets.QLineEdit(ConfigEditDialog)
        self.prefixLineEdit.setObjectName("prefixLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.prefixLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigEditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.nameLabel.setBuddy(self.nameLineEdit)
        self.gameLabel.setBuddy(self.gameLineEdit)
        self.dataLabel.setBuddy(self.dataLineEdit)
        self.modsLabel.setBuddy(self.modsLineEdit)
        self.pluginsLabel.setBuddy(self.pluginsLineEdit)
        self.prefixLabel.setBuddy(self.prefixLineEdit)

        self.retranslateUi(ConfigEditDialog)
        self.buttonBox.accepted.connect(ConfigEditDialog.accept)
        self.buttonBox.rejected.connect(ConfigEditDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigEditDialog)

    def retranslateUi(self, ConfigEditDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigEditDialog.setWindowTitle(_translate("ConfigEditDialog", "Edit Config - Mod Placer"))
        self.nameLabel.setText(_translate("ConfigEditDialog", "Name"))
        self.gameLabel.setText(_translate("ConfigEditDialog", "Nexus game"))
        self.dataLabel.setText(_translate("ConfigEditDialog", "Data directory"))
        self.dataToolButton.setText(_translate("ConfigEditDialog", "..."))
        self.modsLabel.setText(_translate("ConfigEditDialog", "Mods directory"))
        self.modsToolButton.setText(_translate("ConfigEditDialog", "..."))
        self.pluginsLabel.setText(_translate("ConfigEditDialog", "Plugins file"))
        self.pluginsToolButton.setText(_translate("ConfigEditDialog", "..."))
        self.prefixLabel.setText(_translate("ConfigEditDialog", "Plugins line prefix"))


